SELECT
    ObjectID AS object_id,
    Title AS title,
    Date AS creation_date,
    Medium AS medium,
    Dimensions AS dimensions,
    CreditLine AS creditline,
    AccessionNumber AS accession_number,
    DateAcquired AS date_acquired,
    Cataloged AS cataloged,
    URL AS url,
    ImageURL AS image_url,
    OnView AS on_view,
    "Circumference (cm)" AS circumference_cm,
    "Depth (cm)" AS depth_cm,
    "Diameter (cm)" AS diameter_cm,
    "Height (cm)" AS height_cm,
    "Length (cm)" AS length_cm,
    "Weight (kg)" AS weight_kg,
    "Width (cm)" AS width_cm,
    "Seat Height (cm)" AS seat_height_cm,
    "Duration (sec.)" AS duration_sec,
    Classification AS classification,
    Department AS department,
    ConstituentID AS constituent_id
FROM {{ ref('raw_artworks') }}